In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('student_habits_performance.csv')
df.info()

df_original = df.copy()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   student_id                     1000 non-null   str
 1   age                            1000 non-null   int64
 2   gender                         1000 non-null   str
 3   study_hours_per_day            1000 non-null   float64
 4   social_media_hours             1000 non-null   float64
 5   netflix_hours                  1000 non-null   float64
 6   part_time_job                  1000 non-null   str
 7   attendance_percentage          1000 non-null   float64
 8   sleep_hours                    1000 non-null   float64
 9   diet_quality                   1000 non-null   str
 10  exercise_frequency             1000 non-null   int64
 11  parental_education_level       909 non-null    str
 12  internet_quality               1000 non-null   str
 13  mental_health_rating           1000 non-null   int64
 14  extracurricular_participation  1000 non-null   str
 15  exam_score                     1000 non-null   float64
dtypes: float64(6), int64(3), str(7)
memory usage: 156.3 KB

In [3]:
df.head()

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4

In [4]:
df.isnull().sum()

student_id                        0
age                               0
gender                            0
study_hours_per_day               0
social_media_hours                0
netflix_hours                     0
part_time_job                     0
attendance_percentage             0
sleep_hours                       0
diet_quality                      0
exercise_frequency                0
parental_education_level         91
internet_quality                  0
mental_health_rating              0
extracurricular_participation     0
exam_score                        0
dtype: int64

#### Here the parental_education_level has 91 null values, so it must be filled

In [5]:
df['parental_education_level']

0           Master
1      High School
2      High School
3           Master
4           Master
          ...
995    High School
996    High School
997       Bachelor
998       Bachelor
999       Bachelor
Name: parental_education_level, Length: 1000, dtype: str

In [6]:
df['parental_education_level'].unique()

<ArrowStringArray>
['Master', 'High School', 'Bachelor', nan]
Length: 4, dtype: str

In [7]:
df['parental_education_level'].mode()

0    High School
Name: parental_education_level, dtype: str

In [8]:
#We will fill the data using mode imputation technique

mode = df['parental_education_level'].mode()[0]  # [0]-gets the scalar value
df.fillna({'parental_education_level': mode}, inplace=True)

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,S1995,21,Female,2.6,0.5,1.6,No,77.0,7.5,Fair,2,High School,Good,6,Yes,76.1
996,S1996,17,Female,2.9,1.0,2.4,Yes,86.0,6.8,Poor,1,High School,Average,6,Yes,65.9
997,S1997,20,Male,3.0,2.6,1.3,No,61.9,6.5,Good,5,Bachelor,Good,9,Yes,64.4
998,S1998,24,Male,5.4,4.1,1.1,Yes,100.0,7.6,Fair,0,Bachelor,Average,1,No,69.7
999,S1999,19,Female,4.3,2.9,1.9,No,89.4,7.1,Good,2,Bachelor,Average,8,No,74.9

In [9]:
df['parental_education_level'].isnull().sum()

np.int64(0)

In [10]:
df.isnull().sum()

student_id                       0
age                              0
gender                           0
study_hours_per_day              0
social_media_hours               0
netflix_hours                    0
part_time_job                    0
attendance_percentage            0
sleep_hours                      0
diet_quality                     0
exercise_frequency               0
parental_education_level         0
internet_quality                 0
mental_health_rating             0
extracurricular_participation    0
exam_score                       0
dtype: int64

In [11]:
df = df.drop(['student_id'],axis=1)

In [12]:
df.head()

,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4

In [13]:
df['gender'].unique()

<ArrowStringArray>
['Female', 'Male', 'Other']
Length: 3, dtype: str

In [14]:
df['gender'].value_counts()

gender
Female    481
Male      477
Other      42
Name: count, dtype: int64

In [15]:
df = pd.get_dummies(df, columns=['gender'], drop_first=True)

In [16]:
df.columns.tolist()

['age',
 'study_hours_per_day',
 'social_media_hours',
 'netflix_hours',
 'part_time_job',
 'attendance_percentage',
 'sleep_hours',
 'diet_quality',
 'exercise_frequency',
 'parental_education_level',
 'internet_quality',
 'mental_health_rating',
 'extracurricular_participation',
 'exam_score',
 'gender_Male',
 'gender_Other']

In [17]:
df.head()

,age,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score,gender_Male,gender_Other
0,23,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2,False,False
1,20,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0,False,False
2,21,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3,True,False
3,23,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8,False,False
4,19,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4,False,False

In [18]:
df = pd.get_dummies(df, columns=['extracurricular_participation'], drop_first=True)

In [19]:
df.head()

,age,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,exam_score,gender_Male,gender_Other,extracurricular_participation_Yes
0,23,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,56.2,False,False,True
1,20,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,100.0,False,False,False
2,21,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,34.3,True,False,False
3,23,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,26.8,False,False,True
4,19,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,66.4,False,False,False

In [20]:
df['gender_Male'] = df['gender_Male'].astype(int)

In [21]:
df.head()

,age,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,exam_score,gender_Male,gender_Other,extracurricular_participation_Yes
0,23,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,56.2,0,False,True
1,20,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,100.0,0,False,False
2,21,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,34.3,1,False,False
3,23,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,26.8,0,False,True
4,19,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,66.4,0,False,False

In [22]:
df['gender_Other'] = df['gender_Other'].astype(int)
df['extracurricular_participation_Yes'] = df['extracurricular_participation_Yes'].astype(int)

In [23]:
df.head()

,age,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,exam_score,gender_Male,gender_Other,extracurricular_participation_Yes
0,23,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,56.2,0,0,1
1,20,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,100.0,0,0,0
2,21,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,34.3,1,0,0
3,23,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,26.8,0,0,1
4,19,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,66.4,0,0,0

In [24]:
df['part_time_job'].unique()

<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

In [25]:
df['part_time_job'] = df['part_time_job'].map({'Yes':1,'No':0})

In [26]:
df.head()

,age,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,exam_score,gender_Male,gender_Other,extracurricular_participation_Yes
0,23,0.0,1.2,1.1,0,85.0,8.0,Fair,6,Master,Average,8,56.2,0,0,1
1,20,6.9,2.8,2.3,0,97.3,4.6,Good,6,High School,Average,8,100.0,0,0,0
2,21,1.4,3.1,1.3,0,94.8,8.0,Poor,1,High School,Poor,1,34.3,1,0,0
3,23,1.0,3.9,1.0,0,71.0,9.2,Poor,4,Master,Good,1,26.8,0,0,1
4,19,5.0,4.4,0.5,0,90.9,4.9,Fair,3,Master,Good,1,66.4,0,0,0

In [27]:
df['diet_quality'].unique()

<ArrowStringArray>
['Fair', 'Good', 'Poor']
Length: 3, dtype: str

In [28]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder(categories=[['Poor', 'Fair', 'Good']])
df['diet_quality'] = encoder.fit_transform(df[['diet_quality']])

In [29]:
df.head()

,age,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,exam_score,gender_Male,gender_Other,extracurricular_participation_Yes
0,23,0.0,1.2,1.1,0,85.0,8.0,1.0,6,Master,Average,8,56.2,0,0,1
1,20,6.9,2.8,2.3,0,97.3,4.6,2.0,6,High School,Average,8,100.0,0,0,0
2,21,1.4,3.1,1.3,0,94.8,8.0,0.0,1,High School,Poor,1,34.3,1,0,0
3,23,1.0,3.9,1.0,0,71.0,9.2,0.0,4,Master,Good,1,26.8,0,0,1
4,19,5.0,4.4,0.5,0,90.9,4.9,1.0,3,Master,Good,1,66.4,0,0,0

In [30]:
print(df['internet_quality'].unique())
print(df['parental_education_level'].unique())

<ArrowStringArray>
['Average', 'Poor', 'Good']
Length: 3, dtype: str
<ArrowStringArray>
['Master', 'High School', 'Bachelor']
Length: 3, dtype: str

In [31]:
internet_map = {'Poor': 0, 'Average': 1, 'Good': 2}
df['internet_quality'] = df['internet_quality'].map(internet_map)

edu_map = {
    'High School': 0,
    "Bachelor": 1,
    "Master": 2,
}
df['parental_education_level'] = df['parental_education_level'].map(edu_map)

In [32]:
df.head()

,age,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,exam_score,gender_Male,gender_Other,extracurricular_participation_Yes
0,23,0.0,1.2,1.1,0,85.0,8.0,1.0,6,2,1,8,56.2,0,0,1
1,20,6.9,2.8,2.3,0,97.3,4.6,2.0,6,0,1,8,100.0,0,0,0
2,21,1.4,3.1,1.3,0,94.8,8.0,0.0,1,0,0,1,34.3,1,0,0
3,23,1.0,3.9,1.0,0,71.0,9.2,0.0,4,2,2,1,26.8,0,0,1
4,19,5.0,4.4,0.5,0,90.9,4.9,1.0,3,2,2,1,66.4,0,0,0

In [33]:
df.isnull().sum()

age                                  0
study_hours_per_day                  0
social_media_hours                   0
netflix_hours                        0
part_time_job                        0
attendance_percentage                0
sleep_hours                          0
diet_quality                         0
exercise_frequency                   0
parental_education_level             0
internet_quality                     0
mental_health_rating                 0
exam_score                           0
gender_Male                          0
gender_Other                         0
extracurricular_participation_Yes    0
dtype: int64

In [34]:
df.to_csv('../data/processed_data.csv', index=False)

In [35]:
realdf = pd.read_csv('student_habits_performance.csv')

In [36]:
realdf.head()

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4

In [39]:
realdf['internet_quality'].unique()

<ArrowStringArray>
['Average', 'Poor', 'Good']
Length: 3, dtype: str